In [1]:
import numpy as np
np.__version__

'1.20.3'

In [2]:
a=array([1,2,"1"])
print(type(a))

NameError: name 'array' is not defined

In [3]:
classic_list = [1, 2, 3, 5, 7, 11]
type(classic_list)

list

In [4]:
numpy_array = np.array(classic_list)
type(numpy_array)

numpy.ndarray

In [5]:
numpy_array.shape

(6,)

In [6]:
np.array([2,4]).mean()

3.0

In [7]:
numpy_matrix = np.array([[1,2,3], [5,7,11]])
numpy_matrix.shape

(2, 3)

In [ ]:
matrix1 = np.array([
	[1,2,3],
	[4,5,6],
	[7,8,9]
])

In [8]:
matrix1[0, :]

NameError: name 'matrix1' is not defined

In [9]:
matrix1 = np.array([
	[1,2,3],
	[4,5,6],
	[7,8,9]
])
matrix1[0, :]

array([1, 2, 3])

In [10]:
matrix1[:, -1]

array([3, 6, 9])

In [11]:
matrix2 = np.array([
	[1,2,3],
	[0,8,10],
	[1,10,12]
])
matrix2.sum()

47

In [12]:
matrix2.sum(axis=0)

array([ 2, 20, 25])

In [13]:
matrix2.sum(axis=1)

array([ 6, 18, 23])

In [14]:
np.array([1,2]) + np.array([8,9])

array([ 9, 11])

In [15]:
np.array([
	[1,2],
	[3,4]
]) + \
np.array([
	[8,9],
	[10,11]
])

array([[ 9, 11],
       [13, 15]])

In [16]:
import pandas as pd
pd.__version__

'1.2.4'